### PR TITLE
Explain the ASP.NET Core pipeline setup required to use Subscriptions

### PR DESCRIPTION
**Pull request by GoodmanEScott**
While trying to get subscriptions working with Hot Chocolate my team was following the instructions here https://hotchocolate.io/docs/code-first-subscription

But we kept getting this error: "Could not connect to websocket endpoint wss://localhost:5001/graphql. Please check if the endpoint url is correct." 

After looking into the source code, we found middleware that needed to be added but was not documented.

### CODE REVIEW

**Comment by michaelstaib** [comment]
Did you do UseGraphQL? With UseGraphQL subscriptions are also configured.

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/tree/master/examples/AspNetCore.StarWars

**Comment by michaelstaib** [comment]
app
                .UseWebSockets()
                .UseGraphQL("/graphql")

**Comment by GoodmanEScott** [comment]
I'll have to check tomorrow when I get back to work. But I'm 95% sure we
have always called UseGraphQL because you need that to use queries and
mutations?

However, we did not have the UseWebsockets call before. Maybe that was the
necessary and sufficient piece while the call to UseGraphQLSubscription is
superfluous?

**Comment by michaelstaib** [comment]
We have UseGraphQL where everything is included and we have UseGraphQLSubscription, UseGraphQLHttpPost and so on so that you can pick an choose what requests you want to opt-in to.

https://hotchocolate.io/docs/aspnet#asp-net-core-

**Comment by GoodmanEScott** [comment]
Ok, as I suspected, we were already using .UseGraphQL but we were missing the call to .UseWebSockets().  I think your update in 609736a makes sense.

Thanks for your help!

**Pull request merged**
